### ISSUE TITLE
Duplicate image content

### ISSUE THREAD

**Issue by DreymaR** [DreymaR/BigBagKbdTrix#1]
I thought it'd be enough to use the docs/res folder for generic content resources. As it is now, there's a docs/content/img folder and a docs/res folder with subfolders containing the same images etc, and even a docs/res/img folder that looks much like docs/content/img.

I like to refer to the docs/res folder content with external links, and it's sorted thematically. Is that a problem for the page image links in any way? There are no spaces nor special glyphs in file/folder names in there that I know of.

The docs/res/img folder should surely go away soon.

Proposal: Keep the docs/content/img folder for page-specific graphics such as w-img and ico only. For images in the BigBag pages, use the docs/res/ files. Don't change any images in there without asking me first, but preferably use links to those files for the pages. If changing an image for use on the pages is desirable, the edited version of the file can go in docs/content/img for now.

**Comment by abrickinthehallway** [comment]
Cool, I'll remove the docs/res/img duplicate.

We can easily use the docs/res folder for the page image links.

I don't think any editing is needed for any of the images that can't be done solely using CSS, so we should be fine.

**Comment by abrickinthehallway** [comment]
Currently, we don't link to the docs/res folder, but to the dropbox files, like it currently is in the forums, so it's easy to rework the folder structures in docs/content and to delete docs/res/img. After this, I'll update all the links so that they point to the docs/res folder. That's the goal, right?

**Comment by DreymaR** [comment]
The only hitch I've come across was that my job network allowed Dropbox image links but not GitHub links. Not sure how that'll pan out now that we're on another domain. Maybe it'll pass that way, even though my job network is paranoid.  ლ( ʘ▽ʘ)ლ～ORLY

**Comment by abrickinthehallway** [comment]
I removed the duplicates. Currently, only one image link isn't a dropbox one - the first image on the home page.
![image](https://user-images.githubusercontent.com/37268719/110598259-3899b700-818a-11eb-9a39-6aeada516fea.png)
If you see it fine using your job network, Imma update the rest of the links.
